### ISSUE TITLE
base_tag not working

### ISSUE THREAD

**Issue by DesignerX** [camspiers/silverstripe-twig#3]
Hi,
I've tried {{ c.base_tag|raw }}  but it doesnt seem to work and it's causing alot of links to fail.
Any ideas?
Michael,

**Comment by camspiers** [comment]
I haven't tested this, and I should let you know that I don't use SilverStripe or this module any more. But hope this helps!

Probably best to make a trait:

```
trait BaseTag {
  public function BaseTag() {
    return sprint('<base href="%s" />', Director::absoluteBaseURL());
  }
}
```

and then use the trait where you need it:

```
class Page_Controller extends ContentController {
  use BaseTag;
}
```

then in your template:

```
{{ c.BaseTag | raw }}
```
