### ISSUE TITLE
New version tag please

### ISSUE THREAD

**Issue by chris-hall-hu** [camspiers/silverstripe-twig#4]
Hi,
 
Thanks for this very useful have started playing with it.

Could you add a new version tag please, the latest changes to fix for SS 3.1 (and 3.2 now) don't come though when using the composer requirement as described in the readme (I repeated them by hand locally before I realised). 

A new version tag will also ensure people get a later version of twig. 

Thanks again :)

**Comment by camspiers** [comment]
Done :)
